Added MakeFile

diff --git a/restsdn_tui b/restsdn_tui
--- a/restsdn_tui
+++ b/restsdn_tui
@@ -2,14 +2,24 @@
 
 printf "\nStarting Program - SDNBCQKD\n"
 
-CMD=restsdn
+# Checking if the 'restsdn' utility is properly installed.
+which restsdn 1> /dev/null
+if [ $? -ne 0 ]; then
+	echo "The 'restsdn' utility is missing, please fix it with make install!"
+	exit 1
+else
+	CMD=restsdn
+fi
 
+# Parameters for restsdn_net tool
 HOST=localhost
 PORT=1234
 
+# Temporary files
 FILE=/tmp/sdnqkd1-$$
 ERROR=/tmp/sdnqkd-err-$$
 
+# Function to clean up temp files upon exit (Ctrl+C)
 cleanup_exit() {
 	printf "Cleaning up temporary filed before shutdown..."
     rm -f $FILE $ERROR
@@ -17,6 +27,7 @@ cleanup_exit() {
     exit 0
 }
 
+# Function to catch interrupt signal Ctrl+C
 function finish() {
 	printf "\n\nInterrupt signal received! Initiating showdown sequence!"
 	cleanup_exit
@@ -26,6 +37,7 @@ trap finish SIGINT
 #show banner in terminal for TUI, GUI and NET editions 
 cat banner.txt
 
+# Infinite loop to ask for user input on repeat
 while true; do
 	#TEST to see if the Terminal version or the GUI version was called
 	if [ `basename $0` = "restsdn_tui" ]; then
